// Code generated by "stringer -type=GM_EVENT -trimprefix=GME_"; DO NOT EDIT.

package project

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GME_Create-0]
	_ = x[GME_Destroy-1]
	_ = x[GME_Alarm-2]
	_ = x[GME_Step-3]
	_ = x[GME_Collision-4]
	_ = x[GME_Keyboard-5]
	_ = x[GME_Mouse-6]
	_ = x[GME_Other-7]
	_ = x[GME_Draw-8]
	_ = x[GME_KeyPress-9]
	_ = x[GME_KeyRelease-10]
	_ = x[GME_CleanUp-11]
	_ = x[GME_Gesture-12]
	_ = x[GME_COUNT-13]
}

const _GM_EVENT_name = "CreateDestroyAlarmStepCollisionKeyboardMouseOtherDrawKeyPressKeyReleaseCleanUpGestureCOUNT"

var _GM_EVENT_index = [...]uint8{0, 6, 13, 18, 22, 31, 39, 44, 49, 53, 61, 71, 78, 85, 90}

func (i GM_EVENT) String() string {
	if i < 0 || i >= GM_EVENT(len(_GM_EVENT_index)-1) {
		return "GM_EVENT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GM_EVENT_name[_GM_EVENT_index[i]:_GM_EVENT_index[i+1]]
}
