// Code generated by "stringer -type=TOKEN_TYPE -trimprefix=T_"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[T_UNKNOWN-0]
	_ = x[T_IDENT-1]
	_ = x[T_NUMBER-2]
	_ = x[T_STRING-3]
	_ = x[T_DOT-4]
	_ = x[T_SEMICOLON-5]
	_ = x[T_COMMA-6]
	_ = x[T_QUESTION-7]
	_ = x[T_COLON-8]
	_ = x[T_EXCLAM-9]
	_ = x[T_ACC_LIST-10]
	_ = x[T_ACC_MAP-11]
	_ = x[T_ACC_GRID-12]
	_ = x[T_ACC_ARRAY-13]
	_ = x[T_ACC_STRUCT-14]
	_ = x[T_LPAREN-15]
	_ = x[T_RPAREN-16]
	_ = x[T_LSQUARE-17]
	_ = x[T_RSQUARE-18]
	_ = x[T_LCURLY-19]
	_ = x[T_RCURLY-20]
	_ = x[T_LEQ-21]
	_ = x[T_GEQ-22]
	_ = x[T_EQ-23]
	_ = x[T_LESS-24]
	_ = x[T_MORE-25]
	_ = x[T_PLUS-26]
	_ = x[T_MINUS-27]
	_ = x[T_DIV-28]
	_ = x[T_MUL-29]
	_ = x[T_MOD-30]
	_ = x[T_OR-31]
	_ = x[T_AND-32]
	_ = x[T_BITOR-33]
	_ = x[T_BITAND-34]
	_ = x[T_BITNOT-35]
	_ = x[T_BITXOR-36]
	_ = x[T_LSHIFT-37]
	_ = x[T_RSHIFT-38]
	_ = x[T_ASSIGN-39]
	_ = x[T_ASSIGN_ADD-40]
	_ = x[T_ASSIGN_SUB-41]
	_ = x[T_ASSIGN_MUL-42]
	_ = x[T_ASSIGN_DIV-43]
	_ = x[T_DECREMENT-44]
	_ = x[T_INCREMENT-45]
	_ = x[T_HASH-46]
	_ = x[T_BACKSLASH-47]
	_ = x[T_NEWLINE-48]
	_ = x[T_EOF-49]
}

const _TOKEN_TYPE_name = "UNKNOWNIDENTNUMBERSTRINGDOTSEMICOLONCOMMAQUESTIONCOLONEXCLAMACC_LISTACC_MAPACC_GRIDACC_ARRAYACC_STRUCTLPARENRPARENLSQUARERSQUARELCURLYRCURLYLEQGEQEQLESSMOREPLUSMINUSDIVMULMODORANDBITORBITANDBITNOTBITXORLSHIFTRSHIFTASSIGNASSIGN_ADDASSIGN_SUBASSIGN_MULASSIGN_DIVDECREMENTINCREMENTHASHBACKSLASHNEWLINEEOF"

var _TOKEN_TYPE_index = [...]uint16{0, 7, 12, 18, 24, 27, 36, 41, 49, 54, 60, 68, 75, 83, 92, 102, 108, 114, 121, 128, 134, 140, 143, 146, 148, 152, 156, 160, 165, 168, 171, 174, 176, 179, 184, 190, 196, 202, 208, 214, 220, 230, 240, 250, 260, 269, 278, 282, 291, 298, 301}

func (i TOKEN_TYPE) String() string {
	if i < 0 || i >= TOKEN_TYPE(len(_TOKEN_TYPE_index)-1) {
		return "TOKEN_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TOKEN_TYPE_name[_TOKEN_TYPE_index[i]:_TOKEN_TYPE_index[i+1]]
}
